package repeatCA;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Charles Rocha
 */

public class Client extends UnicastRemoteObject implements ClientInterface {
    private ServerInterface server;  // Reference to the server
    private int generatedNumbersCount;  // Counter for generated numbers
    private List<Integer> generatedNumbers;  // List of numbers generated by this client
    private String name;  // Client's name

    protected Client(ServerInterface server) throws RemoteException {
        this.server = server;
        this.generatedNumbersCount = 0;
        this.generatedNumbers = new ArrayList<>();

        // Request the user's name
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter your name: ");
        this.name = scanner.nextLine();
        
        server.connect(this);  // Connect the client to the server
        server.registerName(name);  // Register the client's name on the server
    }

    @Override
    public void startGenerating() throws RemoteException {
        Random random = new Random();
        while (server.getTotal() < 1000000) {
            int randomNumber = random.nextInt(13);
            server.addNumber(randomNumber);
            generatedNumbers.add(randomNumber);
            generatedNumbersCount++;
            System.out.print(randomNumber + ", ");
            if (generatedNumbersCount % 50 == 0) {
                System.out.println();
            }
            try {
                Thread.sleep(1); // Pause for 10 milliseconds
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        printResults();
    }

    private void printResults() throws RemoteException {
        int total = server.getTotal();
        int[] numbers = server.getNumbers();
        
        System.out.println("\nTotal: " + total);
        System.out.println("Generated Numbers by " + name + ":");
        
        for (int i = 0; i < generatedNumbers.size(); i++) {
            System.out.print(generatedNumbers.get(i) + ", ");
            if ((i + 1) % 50 == 0) {
                System.out.println();
            }
        }
        System.out.println();  // Print a new line after printing all numbers
    }
}
