package repeatCA;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Charles Rocha
 */
public class Server extends UnicastRemoteObject implements ServerInterface {
    private List<ClientInterface> clients;  // List of connected clients
    private List<Integer> numList;  // List of generated numbers, as request in CA descriptor
    private int total;  // Total sum of numbers, as request in CA descriptor
    private List<String> clientNames;  // List of client names
    private Map<ClientInterface, List<Integer>> clientNumbers;  // Numbers generated by each client

    protected Server() throws RemoteException {
        clients = new ArrayList<>();
        numList = new ArrayList<>();
        total = 0;
        clientNames = new ArrayList<>();
        clientNumbers = new HashMap<>();
    }

    @Override
    public synchronized void connect(ClientInterface client) throws RemoteException {
        clients.add(client);
        clientNumbers.put(client, new ArrayList<>());
    }

    @Override
    public synchronized void addNumber(int number, ClientInterface client) throws RemoteException {
        numList.add(number);
        total += number;
        clientNumbers.get(client).add(number);
    }

    @Override
    public synchronized int getTotal() throws RemoteException {
        return total;
    }

    @Override
    public synchronized int[] getNumbers() throws RemoteException {
        return numList.stream().mapToInt(i -> i).toArray();
    }

    @Override
    public synchronized void registerName(String name) throws RemoteException {
        clientNames.add(name);
        if (clientNames.size() >= 5) {
            for (ClientInterface client : clients) {
                new Thread(() -> {
                    try {
                        client.startGenerating();
                    } catch (RemoteException e) {
                        e.printStackTrace();
                    }
                }).start();
            }
        }
    }

    public synchronized Map<ClientInterface, List<Integer>> getClientNumbers() {
        return clientNumbers;
    }
}
